# Generated by Django 5.2.1 on 2025-06-05 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Partner Name')),
                ('slug', models.SlugField(allow_unicode=True, help_text='Used for URLs', max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_sku', models.CharField(blank=True, db_index=True, help_text='Stock Keeping Unit, code used by the partner for this product', max_length=128, verbose_name='Partner SKU')),
                ('price_currency', models.CharField(default='THB', max_length=12, verbose_name='Currency')),
                ('price_excl_tax', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (excluding tax)')),
                ('num_in_stock', models.PositiveIntegerField(default=0, verbose_name='Number in Stock')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date Updated')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockrecords', to='catalogue.partner', verbose_name='Partner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockrecords', to='catalogue.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Stock Record',
                'verbose_name_plural': 'Stock Records',
                'ordering': ['-date_created'],
                'unique_together': {('product', 'partner')},
            },
        ),
    ]
