volumes:
  postgres_data:
  redis_data:

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.Django
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "8080:8080"
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./backend:/app/src
    working_dir: /app/src
  web:
    build:
      context: .
      dockerfile: frontend/web/Dockerfile
    container_name: thorpat_web_dev
    working_dir: /app/frontend/web 
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app/frontend
      - ./package.json:/app/package.json
      - /app/frontend/web/node_modules

    ports:
      - "5173:5173"
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile.Django
    restart: always
    command: python -m celery -A thorpat worker -l info
    volumes:
      - ./backend:/app/src
    working_dir: /app/src
    env_file:
      - .env
    depends_on:
      - django
      - redis
      - db
