volumes:
  postgres_data:

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    working_dir: /app/src
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
