# Generated by Django 5.2.1 on 2025-06-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitylog',
            table='activity_log',
        ),
    ]
