# Generated by Django 5.2.1 on 2025-06-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='cartline',
            table='cart_line',
        ),
    ]
