# Generated by Django 5.2.1 on 2025-06-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billingaddress',
            table='billing_address',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderline',
            table='order_line',
        ),
        migrations.AlterModelTable(
            name='shippingaddress',
            table='shipping_address',
        ),
    ]
