# Generated by Django 5.2.1 on 2025-06-16 05:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_product_user_productcategory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cost Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Low Stock Threshold'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='num_allocated',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number Allocated'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='price_incl_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price (including tax)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='price_excl_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price (excluding tax)'),
        ),
    ]
