# Generated by Django 5.2.1 on 2025-06-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_product_dimensions_product_manufacturer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockrecord',
            old_name='partner_sku',
            new_name='sku',
        ),
    ]
