# Generated by Django 5.2.1 on 2025-06-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Partner Name')),
                ('slug', models.SlugField(allow_unicode=True, help_text='Used for URLs', max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'db_table': 'catalogue_partner',
                'ordering': ['name'],
            },
        ),
    ]
